### ISSUE TITLE
Unable to push to documentation branch

### ISSUE THREAD

**Issue by dcrawfo2** [ConfederationC/2017_Project#5]
Trying to push my changes to the documentation branch, but i'm getting this error:
remote: Permission to ConfederationC/2017_Project.git denied to dcrawfo2.

**Comment by phuerta2** [comment]
I have the same error
![27044727_10155063192076560_226281805_n](https://user-images.githubusercontent.com/35505679/35198952-3cacddee-febc-11e7-80c0-813b14cf3ea8.png)

**Comment by KaukinenConfed** [comment]
dcrawfo2 - you have not accepted the invitation to the ConfederationC organization. The invite was sent to the email you used to create your account. Once accepted, you should have access.

**Comment by dcrawfo2** [comment]
Works fine now, thanks!
